// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo4X_1GIgTPwXDFH2o_QzTo013balqsnw',
    appId: '1:251164751858:web:b480b0c9813615c6ab5d6b',
    messagingSenderId: '251164751858',
    projectId: 'pfa2-ce6f7',
    authDomain: 'pfa2-ce6f7.firebaseapp.com',
    storageBucket: 'pfa2-ce6f7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWd-BatSgMxp2CbyJ4FBTWA2wFIOLxPIg',
    appId: '1:251164751858:android:749e72d30f6fc573ab5d6b',
    messagingSenderId: '251164751858',
    projectId: 'pfa2-ce6f7',
    storageBucket: 'pfa2-ce6f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBv-gDg4YLAPt_SIhf1FjUj92FHiqqYQV8',
    appId: '1:251164751858:ios:cfb6180b34f278fcab5d6b',
    messagingSenderId: '251164751858',
    projectId: 'pfa2-ce6f7',
    storageBucket: 'pfa2-ce6f7.appspot.com',
    iosClientId: '251164751858-m1l2o9q4k0tf1lkllgu3gojogd74a6k3.apps.googleusercontent.com',
    iosBundleId: 'com.pfa2.app',
  );
}
